spring:
  profiles:
    active: test
  application:
    name: jira-kpi-service
    is-test: true

  datasource:
    url: jdbc:postgresql://localhost:5432/vendor_analytics
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  http:
    codecs:
      max-in-memory-size: 10MB # TODO: need to research how to handle many data
  codec:
    max-in-memory-size: 10MB

jira:
  base-url: ${{ JIRA_BASE-URL }}
  username: ${{ JIRA_USERNAME }}
  token: ${{ JIRA_TOKEN }}
#  project-keys: ${{ JIRA_PROJECT-KEYS }}
  project-keys: SIDH #only one project in jira
elastic:
  host: localhost
  port: 9200

scheduler:
  full-sync-cron: "0 2 * * * SAT"      # weekly full refresh
  incremental-cron: "0 2 * * * SAT" # every 30 min
#  incremental-cron: "0 * * * * *"
  kpi-calc-cron: "0 4 * * * *"         # 4 AM daily
